### ISSUE TITLE
how to prepare manifest of the dataset

### ISSUE THREAD

**Issue by guobabaya** [Hertin/WavPrompt#2]
I didn't find any useful documents about the scripts in wav2vec repository to generate manifest files (.tsv and .ltr) for LibriSpeech. Could you please provide some related links or teaching? Thank you very much.

**Comment by Hertin** [comment]
The wav2vec website (https://github.com/pytorch/fairseq/tree/main/examples/wav2vec) contains scripts for generating the tsv files and the ltr files.
