### ISSUE TITLE
预训练wavprompt模型正向传播时的参数获取。

### ISSUE THREAD

**Issue by guobabaya** [Hertin/WavPrompt#6]
你好，高前辈。在预训练的时候 ，wavprompt.py文件里面WavPrompt这个类的forward函数的第一句，encoder_out = self.encoder(tbc=False, **kwargs)  这一句并没有传入语音参数source和padding_mask 。但是debug时候在这两个参数在Wav2VecEncoder的forward函数中是可以获取到的，请问是在哪里将参数传入的，我很疑惑，希望能得到你的解答，谢谢。

**Comment by guobabaya** [comment]
这个fairseq的hytra_train的运行的调用过程感觉太绕了..

**Comment by Hertin** [comment]
这是python的语法，参数在kwargs里面，具体语法可以参考https://stackoverflow.com/questions/36901/what-does-double-star-asterisk-and-star-asterisk-do-for-parameters

**Comment by guobabaya** [comment]
> 这是python的语法，参数在kwargs里面，具体语法可以参考https://stackoverflow.com/questions/36901/what-does-double-star-asterisk-and-star-asterisk-do-for-parameters

非常感谢！
